# Generated by Django 4.1.3 on 2023-03-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_note_owner_alter_note_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date_created',
        ),
    ]
